### ISSUE TITLE
Create Icon representing this workbench (3D Printing Tools WB)

### ISSUE THREAD

**Issue by luzpaz** [mark1791/3D_Printing_Tools#5]
The addon manager has been spruced up and we're planning on adding each workbenches .svg icon to it. See https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by luzpaz** [comment]
It's also possible to post to teh FreeCAD UI/UX subforum and get help from some designers to create the logo .. ?

**Comment by mark1791** [comment]
Hi Luzpaz, i've redefined the WB main icon to 3D_Printing_Tools.svg  located in the \FreeCAD\Mod\3D_Printing_Tools\Resources\icons is there a specific naming convention or location required?

**Comment by luzpaz** [comment]
Looks like you put it in the right place. I'll make a PR to FreeCAD to include your icon in the Addon Manager. Will post PR to here soon.

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/pull/2312

**Comment by luzpaz** [comment]
Thanks! Closing
